### ISSUE TITLE
segfault on unknown list_consumer_group_offsets

### ISSUE THREAD

**Issue by tmanninger** [confluentinc/confluent-kafka-python#1982]
**Problem**: Accessing a non-existing consumer group offsets causes a segmentation fault.

**Steps to Reproduce**:
```python
group = ConsumerGroupTopicPartitions(group_id = "non-existing-group")
kafkaAdmin.list_consumer_group_offsets([group])["not-existing-group"].result()
```

**Expected Behavior**:
This should throw an exception (like KafkaException or KeyError), not cause a segmentation fault.

**Actual Behavior**:
A segmentation fault occurs when trying to access a non-existing consumer group.

Version: confluent-kafka-python 2.10.0

**Comment by MSeal** [comment]
This is now fixed and will be in the next beta release as well as next full release.

**Comment by tmanninger** [comment]
@MSeal [v2.13.0b1](https://github.com/confluentinc/confluent-kafka-python/releases/tag/v2.13.0b1)
This release doesn't fix the issue.

it still throws a segemenation fault
